version: '3'
services:
  appfront:
    image: bougis/projet_fil_rouge:front
    ports:
    - "4200:4200"
    depends_on:
    - mypostgres
  appback:
    image: bougis/projet_fil_rouge:back
    ports:
    - "8080:8080"
    depends_on:
    - mypostgres
  mypostgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=admin
     - POSTGRES_USER=postgres
     - POSTGRES_DB=collecte_collaborateur
